# Pipeline to build and release the ARC feedback application
trigger: none
pr: none
appendCommitMessageToRunName: true

pool:
# we need an agent which has Docker installed
 name: Default
 demands:
 - Agent.Name -equals vmlsha1

resources:
- repo: self

variables:
  - group: arc-feedback

  # Azure container registry connection details
  - name: azureSubscription
    value: 'svc-con-awh-01'
  - name: dockerRegistryServerURL
    value: 'duuksawhacr01.azurecr.io'

  # Docker Image Names (under arc/ namespace)
  - name: dockerNamespace
    value: 'arc'
  - name: image
    value: 'arc-feedback'
  - name: tag
    value: 'latest'

  # Azure App Service app name
  - name: appName
    value: 'duuksawh-arc-feedback01'
  - name: appResourceGroupName
    value: 'duuksawh-arc-feedback'

jobs:
  - job: release
    displayName: Release app to Azure App Service Environment
    steps:

      #https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v5
      # Front
      - task: AzureRmWebAppDeployment@5
        displayName: Deploy ARC Feedback Application
        inputs:
          appType: 'webAppContainer'
          deployToSlotOrASE: true
          azureSubscription: '$(azureSubscription)'
          ResourceGroupName: '$(appResourceGroupName)'
          WebAppName: '$(appName)'
          DockerNamespace: '$(dockerRegistryServerURL)'
          DockerRepository: '$(dockerNamespace)/$(image)'
          DockerImageTag: $(tag)
          appSettings: >-
            -DOCKER_REGISTRY_SERVER_URL "https://$(dockerRegistryServerURL)"
            -DOCKER_REGISTRY_SERVER_USERNAME "$(DOCKER_REGISTRY_SERVER_USERNAME)"
            -DOCKER_REGISTRY_SERVER_PASSWORD "$(DOCKER_REGISTRY_SERVER_PASSWORD)"
            -WEBSITES_PORT "8080"
            -ORCID_CLIENT_ID "$(ORCID_CLIENT_ID)"
            -ORCID_CLIENT_SECRET "$(ORCID_CLIENT_SECRET)"
            -APP_SECRET_KEY "$(APP_SECRET_KEY)"
            -DB_USER "$(DB_USER)"
            -DB_PASS "$(DB_PASS)"
            -DB_NAME "$(DB_NAME)"
            -POSTGRES_HOST "$(POSTGRES_HOST)"
            -POSTGRES_PORT "$(POSTGRES_PORT)"
            -DATABASE_URL "$(DATABASE_URL)"
            -ORCID_REDIRECT_URI "$(ORCID_REDIRECT_URI)"
            -ENABLE_ORCID_LOGIN "true"
            -WTF_CSRF_ENABLED "true"
            -DEBUG "false"

      - task: AzureAppServiceManage@0
        displayName: Restart App Service
        inputs:
          azureSubscription: 'svc-con-awh-01'
          Action: 'Restart Azure App Service'
          WebAppName: $(appName)
