"""Add 2 columns to feedback model

Revision ID: 639b7e840675
Revises: f83b92323b4d
Create Date: 2025-07-22 12:20:14.510124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639b7e840675'
down_revision = 'f83b92323b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orcid', sa.String(length=19), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('orcid')

    # ### end Alembic commands ###
