"""empty message

Revision ID: f83b92323b4d
Revises: 47524c1d2ea2
Create Date: 2025-07-21 15:58:51.731644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83b92323b4d'
down_revision = '47524c1d2ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        op.create_table('feedback',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        batch_op.add_column(sa.Column('text', sa.String(length=300), nullable=False))

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index('idx_records_submission_id')
        batch_op.create_index(batch_op.f('ix_records_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_submission_id'))
        batch_op.create_index('idx_records_submission_id', ['submission_id'], unique=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('text')
    op.drop_table('feedback')

    # ### end Alembic commands ###
