"""Initial migration.

Revision ID: 47524c1d2ea2
Revises: 
Create Date: 2025-04-25 11:49:20.880660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47524c1d2ea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcid', sa.String(length=19), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_orcid_name', ['orcid', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_orcid'), ['orcid'], unique=True)

    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcid', sa.String(length=19), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('publication', 'funding', name='record_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orcid'], ['users.orcid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index('idx_record_orcid_type', ['orcid', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_orcid'), ['orcid'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_type'))
        batch_op.drop_index(batch_op.f('ix_records_title'))
        batch_op.drop_index(batch_op.f('ix_records_orcid'))
        batch_op.drop_index(batch_op.f('ix_records_created_at'))
        batch_op.drop_index('idx_record_orcid_type')

    op.drop_table('records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_orcid'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index('idx_user_orcid_name')

    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
